# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      release-tools:
        patterns:
          - "@commitlint/*"
          - "semantic-release"
          - "@semantic-release/*"
      test-tools:
        patterns:
          - "mocha"
          - "nyc"
          - "@istanbuljs/nyc-config-typescript"
      lint-tools:
        patterns:
          - "eslint"
          - "@typescript-eslint/*"
      action-tools:
        patterns:
          - "@actions/*"
